sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - docker

before_install:
  - wget http://sourceforge.net/projects/tango-cs/files/tools/TangORB-8.7.2.jar
  - wget http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.tgz
  - tar xf scala-2.11.7.tgz

before_script:
  - docker build -t mliszcz/tango-cs .
  - CONTAINER=$(docker run -d mliszcz/tango-cs)
  - IPADDR=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' $CONTAINER)
  - TANGO_HOST=${IPADDR}:10000
  - DEVICE="tango://${TANGO_HOST}/sys/database/2"

script:
  - >
    ./scala-2.11.7/bin/scala -cp TangORB-8.7.2.jar
    -e "new fr.esrf.TangoApi.DeviceProxy(\"$DEVICE\")"
